# Generated by Django 4.2.10 on 2025-09-27 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('manual_therapy', 'Manual Therapy'), ('electro_therapy', 'Electro Therapy'), ('laser_therapy', 'Class 4 Laser Therapy / HILT'), ('exercise_fitness', 'Exercise & Fitness'), ('custom_orthotics', 'Custom Orthotics'), ('cupping_therapy', 'Cupping Therapy'), ('orthopaedic_physio', 'Orthopaedic physiotherapy'), ('neuro_physio', 'Neuro physiotherapy'), ('sports_physio', 'Sports physiotherapy'), ('paediatrics_physio', 'Paediatrics physiotherapy'), ('dry_needling', 'Dry needling'), ('physio_at_home', 'Physiotherapy at Home'), ('female_physio', 'Female Physio'), ('chest_physio', 'Chest Physiotherapy'), ('osteopathy', 'Osteopathy Services'), ('tele_physio', 'Tele Physiotherapy'), ('chiropractic', 'Chiropractic Therapy'), ('obesity_physio', 'Obesity Physiotherapy'), ('iastm_therapy', 'IASTM Therapy'), ('vertigo_testing', 'Vertigo Testing'), ('shockwave_therapy', 'Shockwave Therapy')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('age', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
