# Generated by Django 4.2.10 on 2025-09-27 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('concern_type', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('back_pain', 'Back Pain'), ('neck_pain', 'Neck Pain'), ('joint_pain', 'Joint Pain'), ('sports_injury', 'Sports Injury'), ('post_surgery_recovery', 'Post-Surgery Recovery'), ('neurological_condition', 'Neurological Condition'), ('pediatric_care', 'Pediatric Care'), ('home_visit_request', 'Home Visit Request'), ('online_consultation', 'Online Consultation'), ('emergency_care', 'Emergency Care'), ('other', 'Other')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
